# On community clusters, we can use up to 8 CPUs and up to 24 GB of memory.
# However, using less usually means we get workers more quickly.
resources_template: &RESOURCES_TEMPLATE
  cpu: 4
  memory: 16GB

# Run only when pushing to main or in PRs.
branch_filter: &BRANCH_FILTER
  only_if: >
    $CIRRUS_PR != '' ||
    $CIRRUS_BRANCH == 'main'

# FreeBSD 14.2 EOL: November 2028
freebsd14_task:
  freebsd_instance:
    image_family: freebsd-14-2
    << : *RESOURCES_TEMPLATE
  prepare_script: .ci/freebsd-14/prepare.sh
  build_script: .ci/run.sh build .ci/freebsd-14/debug.cmake . build
  test_script: .ci/run.sh test build net.udp_datagram_socket
  always:
    robot_artifacts:
      path: "build/robot-output/**"
  << : *BRANCH_FILTER
