# the used GCC binary
CXX = /opt/local/bin/g++-mp-4.6

# compiler flags
#CXXFLAGS = -std=c++0x -pedantic -Wall -Wextra -O2 -I/opt/local/include/ -fpermissive
CXXFLAGS = -std=c++0x -pedantic -Wall -Wextra -g -O0 -I/opt/local/include/ -fpermissive

# external libraries
LIBS = -L/opt/local/lib -lboost_thread-mt

# external include directories
INCLUDES =
