// clang-format off
// DO NOT EDIT: this file is auto-generated by caf-generate-enum-strings.
// Run the target update-enum-strings if this file is out of sync.
#include "caf/net/basp/connection_state.hpp"

#include <string>

namespace caf {
namespace net {
namespace basp {

std::string to_string(connection_state x) {
  switch(x) {
    default:
      return "???";
    case connection_state::await_handshake_header:
      return "await_handshake_header";
    case connection_state::await_handshake_payload:
      return "await_handshake_payload";
    case connection_state::await_header:
      return "await_header";
    case connection_state::await_payload:
      return "await_payload";
    case connection_state::shutdown:
      return "shutdown";
  };
}

} // namespace basp
} // namespace net
} // namespace caf
