// clang-format off
// DO NOT EDIT: this file is auto-generated by caf-generate-enum-strings.
// Run the target update-enum-strings if this file is out of sync.
#include "caf/net/operation.hpp"

#include <string>

namespace caf {
namespace net {

std::string to_string(operation x) {
  switch(x) {
    default:
      return "???";
    case operation::none:
      return "none";
    case operation::read:
      return "read";
    case operation::write:
      return "write";
    case operation::read_write:
      return "read_write";
    case operation::shutdown:
      return "shutdown";
  };
}

} // namespace net
} // namespace caf
