set(LABEL_EXPR "$ENV{label_exp}")
if ("${LABEL_EXPR}" MATCHES "gcc")
  message(STATUS "Set CXX to g++ based on label_expr content")
  set(CMAKE_C_COMPILER "gcc" CACHE PATH "c++ compiler option")
  set(CMAKE_CXX_COMPILER "g++" CACHE PATH "c++ compiler option")
elseif ("${LABEL_EXPR}" MATCHES "clang")
  message(STATUS "Set CXX to clang++ based on label_expr content")
  set(CMAKE_C_COMPILER "clang" CACHE STRING "c++ compiler option")
  set(CMAKE_CXX_COMPILER "clang++" CACHE STRING "c++ compiler option")
endif()
