name: quality-checks

on:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/CMakeLists.txt'
      - 'cmake/**'
      - '.github/workflows/**'
      - 'scripts/cppcheck.sh'
      - '.cppcheck-suppressions'
  push:
    branches:
      - main

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format-19
        run: |
          sudo apt-get update -y \
            && sudo apt-get install -y --no-install-recommends \
              clang-format-19
      - name: clang-format
        run: |
          find libcaf* -name '*.[ch]pp' | xargs clang-format-19 --dry-run --Werror

  spell-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: spell-checking
        uses: crate-ci/typos@master
        with:
          config: .typos-config.toml

  forbidden-includes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: forbidden-includes
        run: |
          find libcaf_* -name '*hpp' -type f | grep -v 'caf/internal/' | xargs python3 scripts/forbidden-includes-check.py

  type-id-block-offsets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: type-id-block-offsets
        run: python3 scripts/get-next-free-block-offset.py 1>/dev/null && echo OK

  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cppcheck
        run: |
          sudo apt-get update -y \
            && sudo apt-get install -y --no-install-recommends \
              cppcheck \
              jq
      - name: Create compile database for cppcheck
        run: ./configure
      - name: Run full cppcheck on main
        if: github.ref_name == 'main'
        run: scripts/cppcheck.sh
      - name: Run cppcheck on modified modules
        if: github.ref_name != 'main'
        # note: add 'build' so the list is never empty;
        #       the directory has auto-generated sources and is fast to scan
        run: scripts/cppcheck.sh build $( git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -oE 'examples|libcaf_[a-z]+' | sort -u )
      - name: Upload cppcheck report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          if-no-files-found: warn
          path: |
            cppcheck-report.xml
            cppcheck-report-html/
